### ISSUE TITLE
version 0.0.11 requires yaji

### ISSUE THREAD

**Issue by lostpupil** [fnproject/fdk-ruby#12]
```
source 'https://rubygems.org'
gem 'json', '~> 2.0'
gem 'yajl-ruby'
gem 'fdk', '>= 0.0.8', '< 2.0.0'
```
Actually, I need to add third party libraries to make these fdk work.

And there is nothing on this particular change in doc,.
Also, I think this should be a part of fdk itself.

**Comment by crush-157** [comment]
We've dropped `yajl-ruby` as a dependency.

The only gem required is now `fdk`
