### ISSUE TITLE
FDK Ruby generated func.rb returns wrong value with curl

### ISSUE THREAD

**Issue by michael-w-williams** [fnproject/fdk-ruby#7]
The fdk-ruby generated func.rb returns the wrong value when input JSON data in pass from curl. For example

>`curl http://localhost:8080/r/rubyapp/rubyfn -d '{"name": "Bob"}'`

returns

> `{"message":"Hello name!"}`

It should return `{"message":"Hello Bob!"}`.

Using `fn call` works correctly, for example:

> `echo -n '{"name":"Bob"}' | fn call rubyapp /rubyfn`

Returns the correct value of `{"message":"Hello Bob!"}`.

**Comment by treeder** [comment]
Your curl command should set the content type:

```sh
curl -H "Content-Type: application/json"  -d '{"name": "Bob"}' http://localhost:8080/r/rubyapp/rubyfn
```

**Comment by michael-w-williams** [comment]
Sounds good. Thanks. I will be updating the tutorials during the week and will include this as an update.

**Comment by sachin-pikle** [comment]
Now I see this behavior:

$ curl http://localhost:8080/r/rubyapp/rubyfn
{"error":{"message":"container exit code 1"}}

$ curl http://localhost:8080/r/rubyapp/rubyfn -d '{"name":"Bob"}'
{"error":{"message":"container exit code 1"}}

And as Travis suggested:
$ curl -H "Content-Type: application/json" http://localhost:8080/r/rubyapp/rubyfn
{"message":"Hello World!"}

 curl -H "Content-Type: application/json"  -d '{"name": "Bob"}' http://localhost:8080/r/rubyapp/rubyfn
{"message":"Hello Bob!"}

I think it's worth pointing out that other FDKs go, node, etc. do not expect the content-type header. Only the ruby FDK requires this.

**Comment by rdallman** [comment]
preach @sachin-pikle
